# Temporary until we can either kill the circular dependency introduced
# by importing model defs in xmlparser or kill xmlparser entirely

SINGULAR = {
    'acl': 'acl',
    'ad_server': 'ad_servers',
    'advertiser': 'advertisers',
    'agency': 'agencies',
    'atomic_creative': 'atomic_creatives',
    'audience_segment': 'audience_segments',
    'campaign': 'campaigns',
    'concept': 'concepts',
    'contact': 'contacts',
    'creative': 'creatives',
    'creative_approval': 'creative_approvals',
    'deal': 'deals',
    'organization': 'organizations',
    'permission': 'permissions',
    'pixel': 'pixels',
    'pixel_bundle': 'pixel_bundles',
    'pixel_provider': 'pixel_providers',
    'placement_slot': 'placement_slots',
    'publisher': 'publishers',
    'publisher_site': 'publisher_sites',
    'rmx_strategy': 'rmx_strategies',
    'rmx_strategy_roi_target_pixel': 'rmx_strategy_roi_target_pixels',
    'seat': 'seats',
    'site_list': 'site_lists',
    'site_placement': 'site_placements',
    'strategy': 'strategies',
    'strategy_audience_segment': 'strategy_audience_segments',
    'strategy_concept': 'strategy_concepts',
    'strategy_day_part': 'strategy_day_parts',
    'strategy_domain_restriction': 'strategy_domain_restrictions',
    'strategy_supply_source': 'strategy_supply_sources',
    'strategy_targeting_segment': 'strategy_targeting_segments',
    'supply_source': 'supply_sources',
    'target_dimension': 'target_dimensions',
    'target_value': 'target_values',
    'user': 'users',
    'vendor': 'vendors',
    'vendor_contract': 'vendor_contracts',
    'vendor_domain': 'vendor_domains',
    'vendor_pixel': 'vendor_pixels',
    'vendor_pixel_domain': 'vendor_pixel_domains',
    'vertical': 'verticals'
}
